// GlowDeals Authentic Data Store - 100% Real Egyptian & Global Beauty Products
export const DEFAULT_WEBSITES = [
  // Local Egyptian Brands & Marketplaces
  {
    id: "site-hair-addict",
    name: "The Hair Addict",
    domain: "thehairaddict.net",
    url: "https://thehairaddict.net",
    origin: "local",
    country: "Egypt 🇪🇬",
    description: "Egyptian pioneering natural & curly hair care brand.",
    categoryFocus: ["haircare"],
    logoText: "THA",
    status: "active",
    lastChecked: new Date().toISOString()
  },
  {
    id: "site-braes",
    name: "Braes",
    domain: "braes.co",
    url: "https://braes.co",
    origin: "local",
    country: "Egypt 🇪🇬",
    description: "Egyptian clean, sulfate-free haircare and body glowing formulas.",
    categoryFocus: ["haircare", "bodycare"],
    logoText: "BR",
    status: "active",
    lastChecked: new Date().toISOString()
  },
  {
    id: "site-eva",
    name: "Eva Cosmetics",
    domain: "shop.eva-cosmetics.com",
    url: "https://shop.eva-cosmetics.com",
    origin: "local",
    country: "Egypt 🇪🇬",
    description: "Historic Egyptian beauty & personal care brand since 1972.",
    categoryFocus: ["skincare", "bodycare", "nailcare"],
    logoText: "EVA",
    status: "active",
    lastChecked: new Date().toISOString()
  },
  {
    id: "site-raw-african",
    name: "Raw African",
    domain: "rawafrican.net",
    url: "https://rawafrican.net",
    origin: "local",
    country: "Egypt 🇪🇬",
    description: "Egyptian 100% natural and organic beauty & hair solutions.",
    categoryFocus: ["skincare", "haircare", "bodycare"],
    logoText: "RA",
    status: "active",
    lastChecked: new Date().toISOString()
  },
  {
    id: "site-hathor",
    name: "Hathor Organics",
    domain: "hathororganics.com",
    url: "https://hathororganics.com",
    origin: "local",
    country: "Egypt 🇪🇬",
    description: "Egyptian ancient-inspired cold-pressed oils & botanical bodycare.",
    categoryFocus: ["bodycare", "skincare"],
    logoText: "HO",
    status: "active",
    lastChecked: new Date().toISOString()
  },
  {
    id: "site-jumia-eg",
    name: "Jumia Egypt Beauty",
    domain: "jumia.com.eg",
    url: "https://www.jumia.com.eg/health-beauty/",
    origin: "local",
    country: "Egypt 🇪🇬",
    description: "Egypt's large local shopping hub with genuine brand storefronts.",
    categoryFocus: ["makeup", "skincare", "haircare", "nailcare", "bodycare"],
    logoText: "JM",
    status: "active",
    lastChecked: new Date().toISOString()
  },
  {
    id: "site-noon-eg",
    name: "Noon Egypt Beauty",
    domain: "noon.com/egypt-en",
    url: "https://www.noon.com/egypt-en/beauty/",
    origin: "local",
    country: "Egypt 🇪🇬",
    description: "Leading marketplace in Egypt with verified international beauty distributors.",
    categoryFocus: ["makeup", "skincare", "haircare", "bodycare"],
    logoText: "NN",
    status: "active",
    lastChecked: new Date().toISOString()
  },

  // Global Brands & Retailers in Egypt
  {
    id: "site-faces-eg",
    name: "Faces Beauty Egypt",
    domain: "faces.eg",
    url: "https://www.faces.eg",
    origin: "global",
    country: "Global 🌍",
    description: "Premier beauty retailer in Egypt stocking top international cosmetic houses.",
    categoryFocus: ["makeup", "skincare", "nailcare"],
    logoText: "FC",
    status: "active",
    lastChecked: new Date().toISOString()
  },
  {
    id: "site-mazaya-eg",
    name: "Mazaya Stores Egypt",
    domain: "mazaya.eg",
    url: "https://www.mazaya.eg",
    origin: "global",
    country: "Global 🌍",
    description: "Official Egyptian luxury perfumery and European cosmetic distributor.",
    categoryFocus: ["makeup", "skincare"],
    logoText: "MZ",
    status: "active",
    lastChecked: new Date().toISOString()
  },
  {
    id: "site-amazon-eg",
    name: "Amazon Egypt Beauty",
    domain: "amazon.eg",
    url: "https://www.amazon.eg/b?node=21832883031",
    origin: "global",
    country: "Global 🌍",
    description: "Prime express delivery in Egypt for global cosmetics & personal care.",
    categoryFocus: ["makeup", "skincare", "bodycare", "haircare", "nailcare"],
    logoText: "AZ",
    status: "active",
    lastChecked: new Date().toISOString()
  }
];

export const INITIAL_DEALS = [
  {
    id: "deal-hair-addict-recipe",
    title: "The Indian Recipe (Hair Growth & Scalp Stimulant 100% Natural)",
    brand: "The Hair Addict",
    websiteName: "The Hair Addict Official",
    websiteUrl: "https://thehairaddict.net/products/the-indian-recipe",
    category: "haircare",
    origin: "local",
    originBadge: "Egyptian Brand 🇪🇬",
    description: "Egypt's #1 viral hair growth formula with Aloe Vera, Castor Oil, Coconut Oil and Indian Ylang Ylang to stop hair fall and stimulate follicles.",
    originalPrice: 620,
    discountPrice: 495,
    currency: "EGP",
    discountPercent: 20,
    couponCode: "GROW20",
    image: "./assets/images/products/the-indian-recipe.jpg",
    rating: 4.9,
    reviewsCount: 1240,
    isDealOfDay: true,
    badgeText: "🔥 Deal of the Day",
    expiresInHours: 6,
    stockStatus: "Verified Real Deal",
    addedAt: new Date(Date.now() - 3600000).toISOString()
  },
  {
    id: "deal-braes-shimmer-oil",
    title: "Bébé Soleil Golden Hour Shimmering Dry Oil (Tropical Mango & Peach)",
    brand: "Braes",
    websiteName: "Braes Official",
    websiteUrl: "https://braes.co/products/rosee",
    category: "bodycare",
    origin: "local",
    originBadge: "Egyptian Brand 🇪🇬",
    description: "Fast-absorbing glowing dry oil powered by the Braes Glow Complex™ with Papaya, Guava & Vitamin C for face, body, and hair.",
    originalPrice: 650,
    discountPrice: 320,
    currency: "EGP",
    discountPercent: 50,
    couponCode: "BRAES50",
    image: "./assets/images/products/braes-shimmer-oil.png",
    rating: 4.8,
    reviewsCount: 310,
    isDealOfDay: false,
    badgeText: "50% Flash Offer",
    expiresInHours: 12,
    stockStatus: "Verified Real Deal",
    addedAt: new Date(Date.now() - 7200000).toISOString()
  },
  {
    id: "deal-raw-african-routine",
    title: "Twice A Week Oiling Routine (Intense Hair Growth Set)",
    brand: "Raw African",
    websiteName: "Raw African Official",
    websiteUrl: "https://rawafrican.net/products/twice-a-week-oiling-routine-1",
    category: "haircare",
    origin: "local",
    originBadge: "Egyptian Brand 🇪🇬",
    description: "Authentic Egyptian botanical oiling bundle with Follicle Booster and cold-pressed essential oils to combat thinning hair.",
    originalPrice: 580,
    discountPrice: 440,
    currency: "EGP",
    discountPercent: 24,
    couponCode: "RAW24",
    image: "./assets/images/products/raw-african-routine.jpg",
    rating: 4.9,
    reviewsCount: 420,
    isDealOfDay: false,
    badgeText: "Clean Egyptian",
    expiresInHours: 14,
    stockStatus: "Verified Real Deal",
    addedAt: new Date(Date.now() - 10800000).toISOString()
  },
  {
    id: "deal-raw-african-shea",
    title: "Shea Butter Mega Care Set (Pure Unrefined Shea Butter)",
    brand: "Raw African",
    websiteName: "Raw African Official",
    websiteUrl: "https://rawafrican.net/products/shea-butter-mega-set",
    category: "bodycare",
    origin: "local",
    originBadge: "Egyptian Brand 🇪🇬",
    description: "Rich unrefined African & Egyptian whipped shea butter set providing 72 hours of intensive skin hydration and moisture barrier repair.",
    originalPrice: 1169,
    discountPrice: 760,
    currency: "EGP",
    discountPercent: 35,
    couponCode: "SHEA35",
    image: "./assets/images/products/raw-african-shea.png",
    rating: 4.9,
    reviewsCount: 195,
    isDealOfDay: false,
    badgeText: "Mega Bundle",
    expiresInHours: 16,
    stockStatus: "Verified Real Deal",
    addedAt: new Date(Date.now() - 14400000).toISOString()
  },
  {
    id: "deal-eva-peach-lotion",
    title: "Eva Recipe Revival Blend Lotion For Dry Skin - Peach Scent 370ml",
    brand: "Eva Cosmetics",
    websiteName: "Eva Cosmetics Online Shop",
    websiteUrl: "https://shop.eva-cosmetics.com/products/eva-recipe-lotion-for-dry-skin-peach-scent-370-ml-copy",
    category: "bodycare",
    origin: "local",
    originBadge: "Egyptian Brand 🇪🇬",
    description: "Delightfully scented peach body lotion enriched with Argan Oil, Avocado Oil, and Shea Butter to restore rough skin integrity.",
    originalPrice: 175,
    discountPrice: 148,
    currency: "EGP",
    discountPercent: 15,
    couponCode: "EVA15",
    image: "./assets/images/products/eva-peach-lotion.png",
    rating: 4.7,
    reviewsCount: 520,
    isDealOfDay: false,
    badgeText: "Best Seller 🇪🇬",
    expiresInHours: 20,
    stockStatus: "Verified Real Deal",
    addedAt: new Date(Date.now() - 18000000).toISOString()
  },
  {
    id: "deal-eva-cozy-dream",
    title: "Eva Senses Body Splash Cozy Dream 85ml (Coconut & Vanilla)",
    brand: "Eva Cosmetics",
    websiteName: "Eva Cosmetics Online Shop",
    websiteUrl: "https://shop.eva-cosmetics.com/products/eva-skin-care-senses-body-splash-cozy-dream-85-ml",
    category: "bodycare",
    origin: "local",
    originBadge: "Egyptian Brand 🇪🇬",
    description: "A sparkling, sweet fragrance mist with notes of coconut, vanilla, cherry, and rose. Lightweight and long-lasting for daily wear.",
    originalPrice: 100,
    discountPrice: 90,
    currency: "EGP",
    discountPercent: 10,
    couponCode: "SENSES10",
    image: "./assets/images/products/eva-cozy-dream.jpg",
    rating: 4.8,
    reviewsCount: 380,
    isDealOfDay: false,
    badgeText: "Special Price",
    expiresInHours: 24,
    stockStatus: "Verified Real Deal",
    addedAt: new Date(Date.now() - 21600000).toISOString()
  },
  {
    id: "deal-hathor-bath-salts",
    title: "Hathor Organics Mineral-Rich Scented Bath Salts (Oud & Rose Vanilla)",
    brand: "Hathor Organics",
    websiteName: "Hathor Organics Official",
    websiteUrl: "https://hathororganics.com/products/bath-salts",
    category: "bodycare",
    origin: "local",
    originBadge: "Egyptian Brand 🇪🇬",
    description: "Inspired by ancient Egyptian royal bath rituals. Natural mineral salts scented with Oud and Damask Rose for relaxation and muscle detox.",
    originalPrice: 350,
    discountPrice: 250,
    currency: "EGP",
    discountPercent: 28,
    couponCode: "HATHOR28",
    image: "./assets/images/products/hathor-bath-salts.jpg",
    rating: 4.9,
    reviewsCount: 160,
    isDealOfDay: false,
    badgeText: "Ancient Egyptian",
    expiresInHours: 18,
    stockStatus: "Verified Real Deal",
    addedAt: new Date(Date.now() - 25200000).toISOString()
  },
  {
    id: "deal-hathor-rose-water",
    title: "Natural Egyptian Roses Face Mist & Balancing Toner 100ml",
    brand: "Hathor Organics",
    websiteName: "Hathor Organics Official",
    websiteUrl: "https://hathororganics.com/products/rose-water",
    category: "skincare",
    origin: "local",
    originBadge: "Egyptian Brand 🇪🇬",
    description: "Pure distilled Egyptian roses enriched with Collagen and Frankincense to firm skin, shrink pores, and impart instant floral radiance.",
    originalPrice: 950,
    discountPrice: 750,
    currency: "EGP",
    discountPercent: 21,
    couponCode: "ROSE21",
    image: "./assets/images/products/hathor-rose-water.jpg",
    rating: 5.0,
    reviewsCount: 220,
    isDealOfDay: false,
    badgeText: "Pure Roses",
    expiresInHours: 15,
    stockStatus: "Verified Real Deal",
    addedAt: new Date(Date.now() - 28800000).toISOString()
  },
  {
    id: "deal-maybelline-matte-ink",
    title: "Maybelline SuperStay Matte Ink Liquid Lipstick - Shade 15 Lover",
    brand: "Maybelline New York",
    websiteName: "Faces Beauty Egypt",
    websiteUrl: "https://www.faces.eg/en/p/maybelline-superstay-matte-ink-liquid-lipstick-P000000000000107297.html",
    category: "makeup",
    origin: "global",
    originBadge: "Global Retailer 🌍",
    description: "Up to 16 hours of transfer-proof matte liquid lipstick in Egypt's most requested everyday mauve-pink shade (#15 Lover).",
    originalPrice: 320,
    discountPrice: 240,
    currency: "EGP",
    discountPercent: 25,
    couponCode: "MATTE25",
    image: "./assets/images/products/maybelline-matte-ink.jpg",
    rating: 4.8,
    reviewsCount: 840,
    isDealOfDay: false,
    badgeText: "Top Trending",
    expiresInHours: 11,
    stockStatus: "Verified Real Deal",
    addedAt: new Date(Date.now() - 32400000).toISOString()
  },
  {
    id: "deal-maybelline-sky-high",
    title: "Maybelline Lash Sensational Sky High Washable Mascara (01 Very Black)",
    brand: "Maybelline New York",
    websiteName: "Noon Egypt",
    websiteUrl: "https://www.noon.com/egypt-en/lash-sensational-sky-high-washable-mascara-01-very-black-7-2ml/N44005886A/p/",
    category: "makeup",
    origin: "global",
    originBadge: "Global Retailer 🌍",
    description: "Full volume and limitless length mascara with flex tower brush and bamboo extract for dramatic lash definition without clumping.",
    originalPrice: 480,
    discountPrice: 365,
    currency: "EGP",
    discountPercent: 24,
    couponCode: "SKY24",
    image: "./assets/images/products/maybelline-sky-high.jpg",
    rating: 4.9,
    reviewsCount: 1650,
    isDealOfDay: false,
    badgeText: "Viral Hit",
    expiresInHours: 9,
    stockStatus: "Verified Real Deal",
    addedAt: new Date(Date.now() - 36000000).toISOString()
  },
  {
    id: "deal-loreal-infallible",
    title: "L'Oréal Paris Infallible 24H Fresh Wear Liquid Foundation",
    brand: "L'Oréal Paris",
    websiteName: "Amazon Egypt Beauty",
    websiteUrl: "https://www.amazon.eg/dp/B0855G6V1B",
    category: "makeup",
    origin: "global",
    originBadge: "Global Retailer 🌍",
    description: "Breathable, sweat-resistant full coverage liquid foundation with SPF 25. Delivers all-day velvety matte finish with zero transfer.",
    originalPrice: 650,
    discountPrice: 469,
    currency: "EGP",
    discountPercent: 28,
    couponCode: "LOREAL28",
    image: "./assets/images/products/loreal-infallible.jpg",
    rating: 4.7,
    reviewsCount: 920,
    isDealOfDay: false,
    badgeText: "Prime Offer",
    expiresInHours: 13,
    stockStatus: "Verified Real Deal",
    addedAt: new Date(Date.now() - 39600000).toISOString()
  },
  {
    id: "deal-garnier-micellar",
    title: "Garnier SkinActive Micellar Cleansing Water All-in-1 (400ml)",
    brand: "Garnier",
    websiteName: "Jumia Egypt Beauty",
    websiteUrl: "https://www.jumia.com.eg/garnier-skinactive-micellar-cleansing-water-400ml-19430154.html",
    category: "skincare",
    origin: "global",
    originBadge: "Global Retailer 🌍",
    description: "Cleanses, lifts makeup, and calms sensitive skin in one gentle cotton pad swipe with zero rinsing needed. Dermatologist approved in Egypt.",
    originalPrice: 260,
    discountPrice: 175,
    currency: "EGP",
    discountPercent: 33,
    couponCode: "CLEAN33",
    image: "./assets/images/products/garnier-micellar.jpg",
    rating: 4.9,
    reviewsCount: 2400,
    isDealOfDay: false,
    badgeText: "Pharmacy Favorite",
    expiresInHours: 8,
    stockStatus: "Verified Real Deal",
    addedAt: new Date(Date.now() - 43200000).toISOString()
  },
  {
    id: "deal-sally-hansen-nails",
    title: "Sally Hansen Hard As Nails Strengthening Clear Polish Treatment",
    brand: "Sally Hansen",
    websiteName: "Mazaya Stores Egypt",
    websiteUrl: "https://www.mazaya.eg",
    category: "nailcare",
    origin: "global",
    originBadge: "Global Retailer 🌍",
    description: "The original clinic nail treatment formulated with Nylon and Silk protein to harden weak, fragile nails and stop peeling and chipping.",
    originalPrice: 380,
    discountPrice: 285,
    currency: "EGP",
    discountPercent: 25,
    couponCode: "NAILS25",
    image: "./assets/images/products/sally-hansen-nails.jpg",
    rating: 4.8,
    reviewsCount: 310,
    isDealOfDay: false,
    badgeText: "Nail Clinique",
    expiresInHours: 19,
    stockStatus: "Verified Real Deal",
    addedAt: new Date(Date.now() - 46800000).toISOString()
  }
];
