// GlowDeals Initial Data Store - Egyptian & Global Beauty Brands
export const DEFAULT_WEBSITES = [
  // Local Egyptian Brands & Marketplaces
  {
    id: "site-hair-addict",
    name: "The Hair Addict",
    domain: "thehairaddict.net",
    url: "https://thehairaddict.net",
    origin: "local",
    country: "Egypt 🇪🇬",
    description: "Egyptian pioneering natural & curly hair care brand.",
    categoryFocus: ["haircare"],
    logoText: "THA",
    status: "active",
    lastChecked: new Date().toISOString()
  },
  {
    id: "site-source-beauty",
    name: "Source Beauty",
    domain: "sourcebeauty.com",
    url: "https://sourcebeauty.com",
    origin: "local",
    country: "Egypt 🇪🇬",
    description: "Egypt's premier marketplace celebrating Egyptian local beauty brands.",
    categoryFocus: ["skincare", "makeup", "haircare", "bodycare"],
    logoText: "SB",
    status: "active",
    lastChecked: new Date().toISOString()
  },
  {
    id: "site-braes",
    name: "Braes",
    domain: "braes.co",
    url: "https://braes.co",
    origin: "local",
    country: "Egypt 🇪🇬",
    description: "Egyptian clean, sulfate-free haircare and nourishing bodycare.",
    categoryFocus: ["haircare", "bodycare"],
    logoText: "BR",
    status: "active",
    lastChecked: new Date().toISOString()
  },
  {
    id: "site-raw-african",
    name: "Raw African",
    domain: "rawafrican.net",
    url: "https://rawafrican.net",
    origin: "local",
    country: "Egypt 🇪🇬",
    description: "Egyptian 100% natural and organic skincare & haircare solutions.",
    categoryFocus: ["skincare", "haircare", "bodycare"],
    logoText: "RA",
    status: "active",
    lastChecked: new Date().toISOString()
  },
  {
    id: "site-eva",
    name: "Eva Cosmetics",
    domain: "shop.eva-cosmetics.com",
    url: "https://shop.eva-cosmetics.com",
    origin: "local",
    country: "Egypt 🇪🇬",
    description: "Egypt's historic skincare, collagen & anti-aging leader.",
    categoryFocus: ["skincare", "bodycare", "nailcare"],
    logoText: "EVA",
    status: "active",
    lastChecked: new Date().toISOString()
  },
  {
    id: "site-hathor",
    name: "Hathor Organics",
    domain: "hathororganics.com",
    url: "https://hathororganics.com",
    origin: "local",
    country: "Egypt 🇪🇬",
    description: "Ancient Egyptian heritage cold-pressed oils & holistic body care.",
    categoryFocus: ["bodycare", "skincare"],
    logoText: "HO",
    status: "active",
    lastChecked: new Date().toISOString()
  },
  {
    id: "site-jumia-eg",
    name: "Jumia Egypt Beauty",
    domain: "jumia.com.eg",
    url: "https://www.jumia.com.eg/health-beauty/",
    origin: "local",
    country: "Egypt 🇪🇬",
    description: "Mega beauty flash sales, local Egyptian distributor hub.",
    categoryFocus: ["makeup", "skincare", "haircare", "nailcare", "bodycare"],
    logoText: "JM",
    status: "active",
    lastChecked: new Date().toISOString()
  },
  {
    id: "site-noon-eg",
    name: "Noon Egypt Beauty",
    domain: "noon.com/egypt-en",
    url: "https://www.noon.com/egypt-en/beauty/",
    origin: "local",
    country: "Egypt 🇪🇬",
    description: "Daily beauty discounts and yellow Friday sales across Egypt.",
    categoryFocus: ["makeup", "skincare", "haircare", "bodycare"],
    logoText: "NN",
    status: "active",
    lastChecked: new Date().toISOString()
  },

  // Global Brands & Retailers
  {
    id: "site-watsons-eg",
    name: "Watsons Egypt",
    domain: "watsons.com.eg",
    url: "https://watsons.com.eg",
    origin: "global",
    country: "Global 🌍",
    description: "World's leading health & beauty chain operating across Egypt.",
    categoryFocus: ["skincare", "makeup", "nailcare"],
    logoText: "WT",
    status: "active",
    lastChecked: new Date().toISOString()
  },
  {
    id: "site-amazon-eg",
    name: "Amazon Egypt Beauty",
    domain: "amazon.eg",
    url: "https://www.amazon.eg/b?node=21832883031",
    origin: "global",
    country: "Global 🌍",
    description: "Global beauty superstore with Prime express delivery in Cairo & Alex.",
    categoryFocus: ["makeup", "skincare", "bodycare", "haircare", "nailcare"],
    logoText: "AZ",
    status: "active",
    lastChecked: new Date().toISOString()
  },
  {
    id: "site-mazaya",
    name: "Mazaya Stores",
    domain: "mazayastores.com",
    url: "https://mazayastores.com",
    origin: "global",
    country: "Global 🌍",
    description: "Luxury fragrances, French cosmetic houses & prestige skincare.",
    categoryFocus: ["makeup", "skincare"],
    logoText: "MZ",
    status: "active",
    lastChecked: new Date().toISOString()
  },
  {
    id: "site-faces",
    name: "Faces Beauty Egypt",
    domain: "faces.com/eg-en",
    url: "https://www.faces.com/eg-en",
    origin: "global",
    country: "Global 🌍",
    description: "High-end designer beauty, Sephora brand partner in the Middle East.",
    categoryFocus: ["makeup", "skincare", "nailcare"],
    logoText: "FC",
    status: "active",
    lastChecked: new Date().toISOString()
  }
];

export const INITIAL_DEALS = [
  {
    id: "deal-01",
    title: "The Hair Addict Frizz-Off Curl Defining Full Routine",
    brand: "The Hair Addict",
    websiteName: "The Hair Addict",
    websiteUrl: "https://thehairaddict.net",
    category: "haircare",
    origin: "local",
    originBadge: "Egyptian Brand 🇪🇬",
    description: "Complete curly girl method bundle: Shampoo, Deep Conditioner, Leave-In & Curl Glaze with pure macadamia oil.",
    originalPrice: 1250,
    discountPrice: 685,
    currency: "EGP",
    discountPercent: 45,
    couponCode: "CURLY45",
    image: "./assets/images/haircare.jpg",
    rating: 4.9,
    reviewsCount: 380,
    isDealOfDay: true,
    badgeText: "🔥 Deal of the Day",
    expiresInHours: 6,
    stockStatus: "In Stock - High Demand",
    addedAt: new Date(Date.now() - 3600000).toISOString()
  },
  {
    id: "deal-02",
    title: "Raw African Golden Glow Vitamin C + Rose Serum Set",
    brand: "Raw African",
    websiteName: "Raw African",
    websiteUrl: "https://rawafrican.net",
    category: "skincare",
    origin: "local",
    originBadge: "Egyptian Brand 🇪🇬",
    description: "100% cold-pressed organic rosehip & vitamin C booster for instant glass skin radiance and dark spot correction.",
    originalPrice: 720,
    discountPrice: 360,
    currency: "EGP",
    discountPercent: 50,
    couponCode: "RAWAN50",
    image: "./assets/images/skincare.jpg",
    rating: 4.8,
    reviewsCount: 295,
    isDealOfDay: false,
    badgeText: "50% Flash Off",
    expiresInHours: 12,
    stockStatus: "Selling Fast",
    addedAt: new Date(Date.now() - 7200000).toISOString()
  },
  {
    id: "deal-03",
    title: "Fleur de Rose Velvet Matte Lipsticks & Shimmer Palette",
    brand: "Faces Prestige",
    websiteName: "Faces Beauty Egypt",
    websiteUrl: "https://www.faces.com/eg-en",
    category: "makeup",
    origin: "global",
    originBadge: "Global Retailer 🌍",
    description: "Limited edition Parisian rose gold palette with 9 buttery multi-finish eyeshadows and 2 matching velvet lipsticks.",
    originalPrice: 2400,
    discountPrice: 1440,
    currency: "EGP",
    discountPercent: 40,
    couponCode: "ROSEGLOW",
    image: "./assets/images/makeup.jpg",
    rating: 4.9,
    reviewsCount: 512,
    isDealOfDay: false,
    badgeText: "Luxury Deal",
    expiresInHours: 18,
    stockStatus: "Few Remaining",
    addedAt: new Date(Date.now() - 10800000).toISOString()
  },
  {
    id: "deal-04",
    title: "Gluxe Luxury Nail Lacquers & Rose Petal Cuticle Elixir",
    brand: "Gluxe Paris",
    websiteName: "Watsons Egypt",
    websiteUrl: "https://watsons.com.eg",
    category: "nailcare",
    origin: "global",
    originBadge: "Global Retailer 🌍",
    description: "Trio of rose gold shimmer & pastel petal pink non-chip polishes with jojoba-infused nail nourishing oil.",
    originalPrice: 650,
    discountPrice: 390,
    currency: "EGP",
    discountPercent: 40,
    couponCode: "NAILCHIC",
    image: "./assets/images/nail-body.jpg",
    rating: 4.7,
    reviewsCount: 164,
    isDealOfDay: false,
    badgeText: "BOGO 40% Off",
    expiresInHours: 24,
    stockStatus: "In Stock",
    addedAt: new Date(Date.now() - 14400000).toISOString()
  },
  {
    id: "deal-05",
    title: "Braes Rosemary Growth Oil & Scalp Detox Scrub",
    brand: "Braes",
    websiteName: "Braes",
    websiteUrl: "https://braes.co",
    category: "haircare",
    origin: "local",
    originBadge: "Egyptian Brand 🇪🇬",
    description: "Egyptian clean formulation infused with pure rosemary extract and peppermint to stimulate rapid hair growth.",
    originalPrice: 580,
    discountPrice: 348,
    currency: "EGP",
    discountPercent: 40,
    couponCode: "BRAES40",
    image: "./assets/images/haircare.jpg",
    rating: 4.9,
    reviewsCount: 420,
    isDealOfDay: false,
    badgeText: "Clean Egyptian",
    expiresInHours: 9,
    stockStatus: "Popular",
    addedAt: new Date(Date.now() - 18000000).toISOString()
  },
  {
    id: "deal-06",
    title: "Eva Skin Clinic Gold Collagen Youth Restoring Day Cream",
    brand: "Eva Cosmetics",
    websiteName: "Eva Cosmetics",
    websiteUrl: "https://shop.eva-cosmetics.com",
    category: "skincare",
    origin: "local",
    originBadge: "Egyptian Brand 🇪🇬",
    description: "Iconic Egyptian marine collagen infused with 24k gold particles for deep firmness and plumping hydration.",
    originalPrice: 420,
    discountPrice: 270,
    currency: "EGP",
    discountPercent: 36,
    couponCode: "EVACOLLAGEN",
    image: "./assets/images/skincare.jpg",
    rating: 4.6,
    reviewsCount: 680,
    isDealOfDay: false,
    badgeText: "Best Seller 🇪🇬",
    expiresInHours: 15,
    stockStatus: "In Stock",
    addedAt: new Date(Date.now() - 21600000).toISOString()
  },
  {
    id: "deal-07",
    title: "Petal Blossom Whipped Rose Butter & Body Silk Soufflé",
    brand: "Source Beauty Artisan",
    websiteName: "Source Beauty",
    websiteUrl: "https://sourcebeauty.com",
    category: "bodycare",
    origin: "local",
    originBadge: "Egyptian Brand 🇪🇬",
    description: "Decadent Egyptian whipped shea butter infused with Damascene rose essence for 48h velvet skin touch.",
    originalPrice: 490,
    discountPrice: 245,
    currency: "EGP",
    discountPercent: 50,
    couponCode: "BUTTER50",
    image: "./assets/images/nail-body.jpg",
    rating: 4.9,
    reviewsCount: 210,
    isDealOfDay: false,
    badgeText: "Half Price 50%",
    expiresInHours: 7,
    stockStatus: "Limited Batch",
    addedAt: new Date(Date.now() - 25200000).toISOString()
  },
  {
    id: "deal-08",
    title: "Hathor Organics Pure Egyptian Argan & Sweet Almond Body Oil",
    brand: "Hathor Organics",
    websiteName: "Hathor Organics",
    websiteUrl: "https://hathororganics.com",
    category: "bodycare",
    origin: "local",
    originBadge: "Egyptian Brand 🇪🇬",
    description: "Pressed from organic Egyptian harvests. Locks in radiant moisture post-shower with a heavenly natural scent.",
    originalPrice: 380,
    discountPrice: 228,
    currency: "EGP",
    discountPercent: 40,
    couponCode: "HATHOR40",
    image: "./assets/images/nail-body.jpg",
    rating: 4.8,
    reviewsCount: 156,
    isDealOfDay: false,
    badgeText: "Organic Oil",
    expiresInHours: 20,
    stockStatus: "In Stock",
    addedAt: new Date(Date.now() - 28800000).toISOString()
  },
  {
    id: "deal-09",
    title: "Charlotte Tilbury Pillow Talk Cheeks & Lip Glow Set",
    brand: "Charlotte Tilbury",
    websiteName: "Mazaya Stores",
    websiteUrl: "https://mazayastores.com",
    category: "makeup",
    origin: "global",
    originBadge: "Global Retailer 🌍",
    description: "The viral worldwide beauty phenomenon: iconic nude-pink blush and creamy matte lipstick duo.",
    originalPrice: 3200,
    discountPrice: 2080,
    currency: "EGP",
    discountPercent: 35,
    couponCode: "PILLOW35",
    image: "./assets/images/makeup.jpg",
    rating: 5.0,
    reviewsCount: 840,
    isDealOfDay: false,
    badgeText: "Viral Beauty",
    expiresInHours: 11,
    stockStatus: "Only 4 Left",
    addedAt: new Date(Date.now() - 32400000).toISOString()
  },
  {
    id: "deal-10",
    title: "Sally Hansen Complete Salon Manicure Gel Polish Duo",
    brand: "Sally Hansen",
    websiteName: "Amazon Egypt Beauty",
    websiteUrl: "https://www.amazon.eg/b?node=21832883031",
    category: "nailcare",
    origin: "global",
    originBadge: "Global Retailer 🌍",
    description: "Professional UV-free gel shine manicure kit with top coat for up to 14 days of chip-resistant salon nails.",
    originalPrice: 560,
    discountPrice: 336,
    currency: "EGP",
    discountPercent: 40,
    couponCode: "GELNAILS",
    image: "./assets/images/nail-body.jpg",
    rating: 4.5,
    reviewsCount: 310,
    isDealOfDay: false,
    badgeText: "Prime Deal",
    expiresInHours: 14,
    stockStatus: "In Stock",
    addedAt: new Date(Date.now() - 36000000).toISOString()
  }
];
